In [ ]:
!pip install torch==2.2.0 torchvision==0.17.0 timm==0.9.12 numpy==1.26.4 opencv-python-headless==4.8.1.78 -q
import os
os.kill(os.getpid(), 9)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
albucore 0.0.24 requires opencv-python-headless>=4.9.0.80, but you have opencv-python-headless 4.8.1.78 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import zipfile

zip_path = "/content/drive/MyDrive/Faceforensics++/archive (6).zip"
extract_path = "/content/drive/MyDrive/Faceforensics++/"

print("Extracting files...")
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction complete at:", extract_path)

# 1. Organize Files
Sorting extracted files into structured REAL and FAKE folders for binary classification.


In [ ]:
import os
import shutil

extract_path = "/content/drive/MyDrive/celeb_v2"
dataset_path = "/content/drive/MyDrive/CelebDF_dataset"

os.makedirs(f"{dataset_path}/REAL", exist_ok=True)
os.makedirs(f"{dataset_path}/FAKE", exist_ok=True)

real_folders = ["Celeb-real", "YouTube-real"]
fake_folders = ["Celeb-synthesis"]

print("Starting to organize files...")

# REAL
for folder in real_folders:
    src = os.path.join(extract_path, folder)
    if os.path.exists(src):
        for file in os.listdir(src):
            shutil.move(os.path.join(src, file), f"{dataset_path}/REAL")

# FAKE
for folder in fake_folders:
    src = os.path.join(extract_path, folder)
    if os.path.exists(src):
        for file in os.listdir(src):
            shutil.move(os.path.join(src, file), f"{dataset_path}/FAKE")

print("Data organized successfully!")
print("REAL:", len(os.listdir(f"{dataset_path}/REAL")))
print("FAKE:", len(os.listdir(f"{dataset_path}/FAKE")))

Starting to organize files...
Data organized successfully!
REAL: 884
FAKE: 5619


# 2. Data Preprocessing

This section handles loading and preparing the dataset.



# Frames

In [ ]:
import cv2
import os

dataset_path = "/content/drive/MyDrive/CelebDF_dataset"
frames_path = "/content/drive/MyDrive/CelebDF_frames"

os.makedirs(frames_path, exist_ok=True)

def extract_1fps(video_path, output_folder):
    os.makedirs(output_folder, exist_ok=True)
    cap = cv2.VideoCapture(video_path)

 # Get the video frame rate
    fps = cap.get(cv2.CAP_PROP_FPS)
    if fps == 0:
        return

# Save one frame every second
    frame_interval = int(fps)

    frame_id = 0
    saved_id = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break
# Save frame only at each 1-second interval
        if frame_id % frame_interval == 0:
            frame_path = os.path.join(output_folder, f"frame_{saved_id:05d}.jpg")
            cv2.imwrite(frame_path, frame)
            saved_id += 1

        frame_id += 1

    cap.release()

print("Starting frame extraction (1 frame per second)...")

# Extract frames from REAL videos
real_videos = os.listdir(f"{dataset_path}/REAL")
for vid in real_videos:
    video_path = f"{dataset_path}/REAL/{vid}"
    out_folder = f"{frames_path}/REAL/{vid.replace('.mp4','')}"
    extract_1fps(video_path, out_folder)

# Extract frames from FAKE (Deepfake) videos
fake_videos = os.listdir(f"{dataset_path}/FAKE")
for vid in fake_videos:
    video_path = f"{dataset_path}/FAKE/{vid}"
    out_folder = f"{frames_path}/FAKE/{vid.replace('.mp4','')}"
    extract_1fps(video_path, out_folder)

print("Frame extraction completed.")


Starting frame extraction (1 frame per second)...
Frame extraction completed.


# Face Extraction

In [ ]:
!pip install mtcnn==0.1.1
!pip install opencv-python

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 22.9 MB/s eta 0:00:00
  Attempting uninstall: mtcnn
    Found existing installation: mtcnn 1.0.0
    Uninstalling mtcnn-1.0.0:
      Successfully uninstalled mtcnn-1.0.0


In [ ]:
from mtcnn import MTCNN
import cv2
import os

frames_path = "/content/drive/MyDrive/CelebDF_frames"
faces_path = "/content/drive/MyDrive/CelebDF_faces_final"

os.makedirs(faces_path, exist_ok=True)

# Initialize MTCNN face detector
detector = MTCNN()

def extract_face(image_path, output_path):
    img = cv2.imread(image_path)
    if img is None:
        return False
 # Read image and convert from BGR to RGB
    rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Detect faces in the image
    detections = detector.detect_faces(rgb)

    if len(detections) == 0:
        return False   # No face found, skip this frame

  # Crop the first detected face and save it
    x, y, w, h = detections[0]['box']
    x, y = max(0, x), max(0, y)
    face = img[y:y+h, x:x+w]

    cv2.imwrite(output_path, face)
    return True

print("Starting face extraction using MTCNN...")

# Process REAL videos
real_videos = os.listdir(f"{frames_path}/REAL")
for vid in real_videos:
    video_frames_folder = f"{frames_path}/REAL/{vid}"
    output_folder = f"{faces_path}/REAL/{vid}"
    os.makedirs(output_folder, exist_ok=True)

    for frame in os.listdir(video_frames_folder):
        frame_path = f"{video_frames_folder}/{frame}"
        out_path = f"{output_folder}/{frame}"
        extract_face(frame_path, out_path)

# Process FAKE (Deepfake) videos
fake_videos = os.listdir(f"{frames_path}/FAKE")
for vid in fake_videos:
    video_frames_folder = f"{frames_path}/FAKE/{vid}"
    output_folder = f"{faces_path}/FAKE/{vid}"
    os.makedirs(output_folder, exist_ok=True)

    for frame in os.listdir(video_frames_folder):
        frame_path = f"{video_frames_folder}/{frame}"
        out_path = f"{output_folder}/{frame}"
        extract_face(frame_path, out_path)

print("Face extraction completed.")


# Cleaning
Removes corrupted, empty, low-resolution, and invalid face images.

In [ ]:
import os
from PIL import Image
import numpy as np
import signal

faces_path = "/content/drive/MyDrive/CelebDF_faces_final"
min_size = 80 # minimum acceptable image size
deleted = 0
checked = 0

# exception to handle image loading timeout
class TimeoutException(Exception):
    pass

def timeout_handler(signum, frame):
    raise TimeoutException

signal.signal(signal.SIGALRM, timeout_handler)

def is_black_or_empty(img_array):
    return np.mean(img_array) < 5  # almost black image

for root, dirs, files in os.walk(faces_path):
    for file in files:
        if file.lower().endswith((".jpg", ".jpeg", ".png")):
            checked += 1
            file_path = os.path.join(root, file)

            if checked % 300 == 0:
                print(f"Checked {checked} images so far...")

            try:
              # Set 1-second timeout to skip slow/corrupted images
                signal.alarm(1)
                img = Image.open(file_path)
                img_array = np.array(img)
                signal.alarm(0)
                  # Delete small images
                if img.width < min_size or img.height < min_size:
                    os.remove(file_path)
                    deleted += 1
                    print(f"Deleted (small): {file_path}")
                    continue
                  # Delete black or empty images
                if is_black_or_empty(img_array):
                    os.remove(file_path)
                    deleted += 1
                    print(f"Deleted (black/empty): {file_path}")
                    continue

            except TimeoutException:
              # Image took too long to load
                os.remove(file_path)
                deleted += 1
                print(f"Deleted (timeout): {file_path}")

            except Exception:
              # Image is corrupted or unreadable
                os.remove(file_path)
                deleted += 1
                print(f"Deleted (corrupted): {file_path}")

print("Cleaning completed.")
print(f"Total images checked: {checked}")
print(f"Total images deleted: {deleted}")


In [ ]:
import os
import shutil
from pathlib import Path
from tqdm import tqdm


DATASET_1 = "/content/drive/MyDrive/CelebDF_faces/CelebDF_faces_final"
DATASET_2 = "/content/drive/MyDrive/Faceforensics++"
OUTPUT_DIR = "/content/drive/MyDrive/CombaindeFaces"


IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tiff"}

In [ ]:
def collect_images(dataset_path: str, split: str) -> list[Path]:

    split_path = Path(dataset_path) / split
    images = []

    if not split_path.exists():
        print(f"  Warning: Folder not found: {split_path}")
        return images

    # Search through all subdirectories inside real/fake
    for sub_dir in split_path.iterdir():
        if sub_dir.is_dir():
            for file in sub_dir.iterdir():
                if file.suffix.lower() in IMAGE_EXTENSIONS:
                    images.append(file)

    return images

In [ ]:
def copy_images(images: list[Path], output_split_dir: Path, prefix: str):

    output_split_dir.mkdir(parents=True, exist_ok=True)

    for img_path in tqdm(images, desc=f"  Copying {prefix}", unit="image"):

        new_name = f"{prefix}__{img_path.parent.name}__{img_path.name}"
        dest = output_split_dir / new_name

        # Handle duplicate filenames
        counter = 1
        while dest.exists():
            stem = img_path.stem
            suffix = img_path.suffix
            new_name = f"{prefix}__{img_path.parent.name}__{stem}_{counter}{suffix}"
            dest = output_split_dir / new_name
            counter += 1

        shutil.copy2(img_path, dest)

In [ ]:
def merge_datasets():
    print("=" * 55)
    print("Merging Two Datasets (DeepFake Dataset Merger)")
    print("=" * 55)

    output_real = Path(OUTPUT_DIR) / "REAL"
    output_fake = Path(OUTPUT_DIR) / "FAKE"

    for split, output_split_dir in [("REAL", output_real), ("FAKE", output_fake)]:
        print(f"\nProcessing folder: {split.upper()}")

        # Collect images from both datasets
        imgs_ds1 = collect_images(DATASET_1, split)
        imgs_ds2 = collect_images(DATASET_2, split)

        print(f"  Dataset 1: {len(imgs_ds1):,} images")
        print(f"  Dataset 2: {len(imgs_ds2):,} images")
        print(f"  Total    : {len(imgs_ds1) + len(imgs_ds2):,} images")

        # Copy images
        copy_images(imgs_ds1, output_split_dir, prefix="ds1")
        copy_images(imgs_ds2, output_split_dir, prefix="ds2")

    # Final statistics
    print("\n" + "=" * 55)
    print("Merging completed successfully!")
    print(f"Output path: {OUTPUT_DIR}")
    print(f" REAL/ {len(list(output_real.iterdir())):,} images")
    print(f" FAKE/ {len(list(output_fake.iterdir())):,} images")
    print("=" * 55)

In [ ]:
if __name__ == "__main__":
    merge_datasets()

# 3. Model Architecture

This section defines the Xception-based deepfake detection model.

In [ ]:

# ============================================================
# Install required packages
# ============================================================
!pip install timm -q

import os
import shutil
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import timm


In [ ]:

# ============================================================
# Global Settings
# ============================================================
MERGED_DIR  = "/content/drive/MyDrive/CombaindeFaces"
SPLIT_DIR   = "/content/drive/MyDrive/CombinedFaces_split"

TRAIN_RATIO = 0.70
VAL_RATIO   = 0.15
TEST_RATIO  = 0.15

IMG_SIZE    = 299       # Xception native input size
BATCH_SIZE  = 32        # Reduce to 16 if GPU memory is limited
EPOCHS      = 20
LR          = 1e-4
SEED        = 42

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


# Split merged dataset

In [ ]:
def split_dataset():
    print("Splitting dataset ...")

    for class_name in ["REAL", "FAKE"]:
        class_path = Path(MERGED_DIR) / class_name

        if not class_path.exists():
            print(f"  WARNING: folder not found -> {class_path}")
            continue

        images = list(class_path.iterdir())

        # First split: train vs (val + test)
        train_files, val_test_files = train_test_split(
            images,
            test_size=(VAL_RATIO + TEST_RATIO),
            random_state=SEED
        )

        # Second split: val vs test
        val_files, test_files = train_test_split(
            val_test_files,
            test_size=TEST_RATIO / (VAL_RATIO + TEST_RATIO),
            random_state=SEED
        )

        # Copy files into their respective folders
        for subset, files in [("train", train_files),
                               ("val",   val_files),
                               ("test",  test_files)]:
            dest = Path(SPLIT_DIR) / subset / class_name
            dest.mkdir(parents=True, exist_ok=True)
            for f in files:
                shutil.copy2(f, dest / f.name)

        print(f"  {class_name:4s} -> train: {len(train_files):5d} | "
              f"val: {len(val_files):5d} | test: {len(test_files):5d}")

    print("Split complete.")
    print(f"Output: {SPLIT_DIR}")

# DataLoader

In [ ]:
from torch.utils.data import WeightedRandomSampler

def build_dataloaders():
    # normalize to [-1, 1]
    mean = [0.5, 0.5, 0.5]
    std  = [0.5, 0.5, 0.5]

# augmentation for training only
    train_transforms = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])
 # no augmentation for val/test
    eval_transforms = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])

    train_dataset = datasets.ImageFolder(f"{SPLIT_DIR}/train", transform=train_transforms)
    val_dataset   = datasets.ImageFolder(f"{SPLIT_DIR}/val",   transform=eval_transforms)
    test_dataset  = datasets.ImageFolder(f"{SPLIT_DIR}/test",  transform=eval_transforms)

    # handle class imbalance with weighted sampling
    class_counts   = np.bincount(train_dataset.targets)
    class_weights  = 1.0 / class_counts
    sample_weights = [class_weights[t] for t in train_dataset.targets]
    sample_weights = torch.DoubleTensor(sample_weights)

    sampler = WeightedRandomSampler(
        weights     = sample_weights,
        num_samples = len(sample_weights),
        replacement = True
    )

# sampler is used instead of shuffle=True
    train_loader = DataLoader(
        train_dataset,
        batch_size  = BATCH_SIZE,
        sampler     = sampler,
        num_workers = 2,
        pin_memory  = True
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size  = BATCH_SIZE,
        shuffle     = False,
        num_workers = 2,
        pin_memory  = True
    )
    test_loader = DataLoader(
        test_dataset,
        batch_size  = BATCH_SIZE,
        shuffle     = False,
        num_workers = 2,
        pin_memory  = True
    )

    print("DataLoaders ready.")
    print(f"  Classes : {train_dataset.classes}")
    print(f"  Train   : {len(train_dataset)}")
    print(f"  Val     : {len(val_dataset)}")
    print(f"  Test    : {len(test_dataset)}")

    return train_loader, val_loader, test_loader, train_dataset

# Xception model

In [ ]:

def build_model(num_classes=2):
    model = timm.create_model("legacy_xception", pretrained=True, num_classes=num_classes)
    model = model.to(DEVICE)

    print("Model ready.")
    print(f"  Architecture : Xception")
    print(f"  Num classes  : {num_classes}")
    print(f"  Device       : {DEVICE}")

    return model


def build_optimizer(model):
    # lower lr for backbone to avoid overwriting pretrained weights
    backbone_params   = [p for n, p in model.named_parameters() if "fc" not in n]
    classifier_params = [p for n, p in model.named_parameters() if "fc" in n]

    optimizer = torch.optim.AdamW([
        {"params": backbone_params,   "lr": LR * 0.1},
        {"params": classifier_params, "lr": LR},
    ], weight_decay=1e-4)

    return optimizer


# TRAINING LOOP

In [ ]:
model = build_model(num_classes=2)
# load best weights saved during training
model.load_state_dict(torch.load("/content/drive/MyDrive/best_xception.pth",
                                  map_location=DEVICE))
model = model.to(DEVICE)

# resume training from last checkpoint
checkpoint = torch.load("/content/drive/MyDrive/checkpoint_new.pth",
                         map_location=DEVICE)
START_EPOCH  = checkpoint["epoch"] + 1
best_val_acc = checkpoint["best_val_acc"]
print(f"Resuming from epoch {START_EPOCH}")
print(f"Best val acc     : {best_val_acc}")

In [ ]:
def train(model, train_loader, val_loader, train_dataset, best_val_acc=0.0):
    class_counts   = np.bincount(train_dataset.targets)
    class_weights  = 1.0 / class_counts
    weights_tensor = torch.FloatTensor(class_weights).to(DEVICE)
    criterion      = nn.CrossEntropyLoss(weight=weights_tensor)
    optimizer      = build_optimizer(model)
    scheduler      = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)


    patience       = 5
    patience_count = 0

    print("Starting training ...")
    print("-" * 65)

    for epoch in range(START_EPOCH, EPOCHS):

        # --- Training phase ---
        model.train()
        train_loss, correct, total = 0.0, 0, 0

        for imgs, labels in train_loader:
            imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            outputs = model(imgs)
            loss    = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            correct    += (outputs.argmax(1) == labels).sum().item()
            total      += labels.size(0)

        train_acc  = correct / total
        train_loss = train_loss / len(train_loader)

        # --- Validation phase ---
        model.eval()
        val_loss, val_correct, val_total = 0.0, 0, 0

        with torch.no_grad():
            for imgs, labels in val_loader:
                imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
                outputs     = model(imgs)
                val_loss    += criterion(outputs, labels).item()
                val_correct += (outputs.argmax(1) == labels).sum().item()
                val_total   += labels.size(0)

        val_acc  = val_correct / val_total
        val_loss = val_loss / len(val_loader)

        scheduler.step()

      # flag overfitting/underfitting based on train-val gap
        gap = train_acc - val_acc
        if gap > 0.10:
            flag = "  WARNING: Overfitting detected"
        elif train_acc < 0.60:
            flag = "  WARNING: Underfitting"
        else:
            flag = "  Training looks healthy"

        print(f"Epoch [{epoch+1:02d}/{EPOCHS}]  "
              f"Train Loss: {train_loss:.4f}  Train Acc: {train_acc:.4f}  "
              f"Val Loss: {val_loss:.4f}  Val Acc: {val_acc:.4f}  {flag}")

# save best model and reset
        if val_acc > best_val_acc:
            best_val_acc   = val_acc
            patience_count = 0
            torch.save(model.state_dict(), "/content/drive/MyDrive/best_xception.pth")
            torch.save({
                         "epoch"       : epoch,
                         "model_state" : model.state_dict(),
                         "optim_state" : optimizer.state_dict(),
                          "best_val_acc": best_val_acc,
              }, "/content/drive/MyDrive/checkpoint_new.pth")
            print(f"  Saved best model  val_acc={val_acc:.4f}")
        else:
            patience_count += 1
            print(f"  No improvement  patience: {patience_count}/{patience}")
            if patience_count >= patience:
                print("  Early stopping triggered.")
                break

    print("-" * 65)
    print(f"Training complete.  Best val acc: {best_val_acc:.4f}")

# EVALUATION

In [ ]:
def evaluate(model, test_loader, train_dataset):
    # load best weights before evaluation
    model.load_state_dict(torch.load("/content/drive/MyDrive/best_xception.pth"))
    model.eval()

    all_preds  = []
    all_labels = []
    all_probs  = []

    with torch.no_grad():
        for imgs, labels in test_loader:
            imgs    = imgs.to(DEVICE)
            outputs = torch.softmax(model(imgs), dim=1)
            preds   = outputs.argmax(1).cpu().numpy()

            all_preds.extend(preds)
            all_labels.extend(labels.numpy())
            all_probs.extend(outputs[:, 1].cpu().numpy())  # probability of fake class

    print("Test Results")
    print("-" * 65)
    print(classification_report(all_labels, all_preds, target_names=train_dataset.classes))
    print(f"AUC-ROC : {roc_auc_score(all_labels, all_probs):.4f}")
    print("Confusion Matrix:")
    print(confusion_matrix(all_labels, all_preds))


In [ ]:
!pip install mtcnn -q

In [ ]:
!pip install mtcnn lz4 -q

In [ ]:
!pip install facenet-pytorch -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 22.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 47.7 MB/s eta 0:00:00


In [ ]:
def predict(image_path, model):
    from PIL import Image
    from facenet_pytorch import MTCNN as FaceMTCNN
    import numpy as np

    eval_transforms = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
    ])

# detect and crop face from the input image
    detector = FaceMTCNN(keep_all=False)
    img      = Image.open(image_path).convert("RGB")
    face     = detector(img)

    if face is None:
        print("No face detected.")
        return None, None


    face = face.unsqueeze(0).to(DEVICE)

    model.eval()
    with torch.no_grad():
        outputs    = torch.softmax(model(face), dim=1)
        pred_idx   = outputs.argmax(1).item()
        confidence = outputs.max().item() * 100
 # idx 0 = FAKE, idx 1 = REAL
    pred_class = "FAKE" if pred_idx == 0 else "REAL"

    print(f"Result     : {pred_class}")
    print(f"Confidence : {confidence:.1f}%")

    return pred_class, confidence

In [ ]:
def predict_video(video_path, model):
    import cv2
    from PIL import Image
    from torchvision import transforms
    from facenet_pytorch import MTCNN
    import numpy as np

    mtcnn = MTCNN(keep_all=False, device=DEVICE)

    transform = transforms.Compose([
        transforms.Resize((299, 299)),
        transforms.ToTensor(),
        transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
    ])

    def extract_face_mtcnn(frame):
       # convert BGR to RGB
        img = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        boxes, _ = mtcnn.detect(img)

        if boxes is None:
            return None

        x1, y1, x2, y2 = [int(b) for b in boxes[0]]
        w = x2 - x1
        h = y2 - y1
        # add margin around the face box
        margin = int(0.2 * max(w, h))

        x1 = max(0, x1 - margin)
        y1 = max(0, y1 - margin)
        x2 = min(img.width,  x2 + margin)
        y2 = min(img.height, y2 + margin)

        return img.crop((x1, y1, x2, y2))

    # افتح الفيديو
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("ERROR: Could not open video")
        return None, None

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps          = cap.get(cv2.CAP_PROP_FPS)
    duration     = total_frames / fps if fps > 0 else 0

    print(f"Video Info: {total_frames} frames | {fps:.1f} FPS | {duration:.1f} seconds")

    fake_probs  = []
    frame_idx   = 0
    sample_rate = 3 # process every 3rd frame

    model.eval()
    with torch.no_grad():
        while True:
            ret, frame = cap.read()
            if not ret:
                break

            if frame_idx % sample_rate == 0:
                face = extract_face_mtcnn(frame)
                if face is not None:
                    tensor    = transform(face).unsqueeze(0).to(DEVICE)
                    output    = model(tensor)
                    probs     = torch.softmax(output, dim=1)
                    fake_prob = probs[0][0].item()
                    fake_probs.append(fake_prob)

            frame_idx += 1

    cap.release()

    if not fake_probs:
        print("No faces detected in video.")
        return None, None

    avg_fake_prob = np.median(fake_probs)


    print(f"\n{'='*45}")
    print(f"Frames checked : {len(fake_probs)}")
    print(f"Avg FAKE prob  : {avg_fake_prob*100:.1f}%")
    print(f"{'='*45}")

    if avg_fake_prob >= 0.5:
        print(f"Final Verdict  : FAKE ({avg_fake_prob*100:.1f}%)")
    else:
        print(f"Final Verdict  : REAL ({(1-avg_fake_prob)*100:.1f}%)")

    pred_class = "FAKE" if avg_fake_prob >= 0.5 else "REAL"
    confidence = avg_fake_prob * 100 if pred_class == "FAKE" else (1 - avg_fake_prob) * 100

    return pred_class, confidence

In [ ]:
split_dataset()

Splitting dataset ...
  REAL -> train: 14235 | val:  3050 | test:  3051
  FAKE -> train: 25476 | val:  5459 | test:  5460
Split complete.


In [ ]:
train_loader, val_loader, test_loader, train_dataset = build_dataloaders()

DataLoaders ready.
  Classes : ['FAKE', 'REAL']
  Train   : 39711
  Val     : 8509
  Test    : 8511


In [ ]:
model = build_model(num_classes=2)
model = model.to(DEVICE)

print("Model ready.")
print(f"  Architecture : Xception")
print(f"  Num classes  : 2")
print(f"  Device       : {DEVICE}")

Model ready.
  Architecture : Xception
  Num classes  : 2
  Device       : cpu
Model ready.
  Architecture : Xception
  Num classes  : 2
  Device       : cpu


In [ ]:
train(model, train_loader, val_loader, train_dataset)

In [ ]:
model = build_model(num_classes=2)
model.load_state_dict(torch.load("/content/drive/MyDrive/best_xception.pth",
                                  map_location=DEVICE))
model = model.to(DEVICE)
print("Model loaded successfully.")

Model ready.
  Architecture : Xception
  Num classes  : 2
  Device       : cpu
Model loaded successfully.


In [ ]:
evaluate(model, test_loader, train_dataset)

Test Results
-----------------------------------------------------------------
              precision    recall  f1-score   support

        FAKE       0.99      0.98      0.98      5460
        REAL       0.96      0.98      0.97      3051

    accuracy                           0.98      8511
   macro avg       0.97      0.98      0.98      8511
weighted avg       0.98      0.98      0.98      8511

AUC-ROC : 0.9974
Confusion Matrix:
[[5332  128]
 [  65 2986]]


In [ ]:
from google.colab import files
uploaded = files.upload()


image_path = list(uploaded.keys())[0]
predict(image_path, model)

Saving Screenshot 2026-05-21 001718.png to Screenshot 2026-05-21 001718.png
Result     : FAKE
Confidence : 96.8%


('FAKE', 96.77285552024841)

In [ ]:
from google.colab import files
uploaded   = files.upload()
video_path = list(uploaded.keys())[0]

results = predict_video(video_path, model)

Saving 5.mov to 5 (5).mov
Video Info: 241 frames | 24.0 FPS | 10.0 seconds
tensor([[0.5186, 0.4814]])
tensor([[0.9470, 0.0530]])
tensor([[0.9477, 0.0523]])
tensor([[0.9261, 0.0739]])
tensor([[0.9291, 0.0709]])
tensor([[0.9009, 0.0991]])
tensor([[0.8524, 0.1476]])
tensor([[0.9717, 0.0283]])
tensor([[0.8664, 0.1336]])
tensor([[0.9622, 0.0378]])
tensor([[0.9671, 0.0329]])
tensor([[0.9100, 0.0900]])
tensor([[0.9880, 0.0120]])
tensor([[0.9785, 0.0215]])
tensor([[0.8887, 0.1113]])
tensor([[0.9677, 0.0323]])
tensor([[0.9820, 0.0180]])
tensor([[0.9325, 0.0675]])
tensor([[0.9303, 0.0697]])
tensor([[0.8195, 0.1805]])
tensor([[0.9383, 0.0617]])
tensor([[0.9179, 0.0821]])
tensor([[0.8283, 0.1717]])
tensor([[0.8554, 0.1446]])
tensor([[0.9153, 0.0847]])
tensor([[0.7049, 0.2951]])
tensor([[0.8541, 0.1459]])
tensor([[0.9406, 0.0594]])
tensor([[0.5896, 0.4104]])
tensor([[0.8822, 0.1178]])
tensor([[0.9169, 0.0831]])
tensor([[0.8885, 0.1115]])
tensor([[0.9464, 0.0536]])
tensor([[0.9071, 0.0929]])
tensor(

In [ ]:
!pip install -q huggingface_hub

from huggingface_hub import login, HfApi

# Login
login("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")

repo_id = "H831A/Yaqeen.models"

api = HfApi()
api.upload_file(
    path_or_fileobj = "/content/drive/MyDrive/best_xception.pth",
    path_in_repo    = "best_xception.pth",
    repo_id         = repo_id,
    repo_type       = "model"
)

print("Model uploaded successfully!")

Processing Files (0 / 0)      : |          |  0.00B /  0.00B            

New Data Upload               : |          |  0.00B /  0.00B            

  ...MyDrive/best_xception.pth:  10%|9         | 7.98MB / 83.6MB            

Model uploaded successfully!


Grad-CAM

In [ ]:
!pip install grad-cam -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 58.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 84.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
facenet-pytorch 2.6.0 requires numpy<2.0.0,>=1.24.0, but you have numpy 2.4.6 which is incompatible.
albucore 0.0.24 requires opencv-python-headless>=4.9.0.80, but you have opencv-python-headless 4.8.1.78 which is incompatible.
albumentations 2.0.8 requires opencv-python-headless>=4.9.0.80, but you have opencv-python-headless 4.8.1.78 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.6 which is incompatible.


In [ ]:
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import torchvision.transforms as T


model.eval()

# last conv layer in Xception — best layer for GradCAM
target_layers = [model.conv4]


def apply_gradcam(image_path, label=""):
    transform = T.Compose([
        T.Resize((299, 299)),
        T.ToTensor(),
        T.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])
    ])

    img = Image.open(image_path).convert("RGB")
    img_resized = img.resize((299, 299))
    img_array = np.array(img_resized) / 255.0  # normalize to [0, 1] for visualization

    tensor = transform(img).unsqueeze(0).to(DEVICE)


    with GradCAM(model=model, target_layers=target_layers) as cam:
        targets = [ClassifierOutputTarget(0)]  # 0 = FAKE
        grayscale_cam = cam(input_tensor=tensor, targets=targets)
        visualization = show_cam_on_image(
            img_array.astype(np.float32),
            grayscale_cam[0],
            use_rgb=True
        )


    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.imshow(img_resized)
    plt.title(f"Original - {label}")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(visualization)
    plt.title("Grad-CAM Heatmap")
    plt.axis("off")

    plt.tight_layout()
    plt.savefig(f"gradcam_{label}.png", dpi=150)
    plt.show()


from google.colab import files
uploaded = files.upload()
image_path = list(uploaded.keys())[0]


apply_gradcam(image_path, label="FAKE")